import hre from "hardhat";
import fs from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const artifactPath = path.resolve(
  __dirname,
  "../artifacts/contracts/CertificateRegistry.sol/CertificateRegistry.json"
);
const constantsPath = path.resolve(
  __dirname,
  "../../frontend/src/config/constants.js"
);

async function main() {
  try {
    console.log("🚀 Deploying CertificateRegistry...");
    const { ethers } = await hre.network.connect();
    const [deployer] = await ethers.getSigners();
    const balance = await ethers.provider.getBalance(deployer.address);

    console.log(`📬 Deployer: ${deployer.address}`);
    console.log(`💰 Balance: ${ethers.formatEther(balance)} ETH`);

    const Registry = await ethers.getContractFactory("CertificateRegistry");
    const registry = await Registry.deploy();
    await registry.waitForDeployment();

    const address = await registry.getAddress();
    const receipt = await registry.deploymentTransaction()?.wait();

    console.log(`✅ Contract deployed to: ${address}`);
    console.log(`📦 Block number: ${receipt?.blockNumber ?? "unknown"}`);

    const artifact = JSON.parse(await fs.readFile(artifactPath, "utf8"));
    await fs.mkdir(path.dirname(constantsPath), { recursive: true });
    await fs.writeFile(
      constantsPath,
      `// Auto-generated by deploy script\nexport const CONTRACT_ADDRESS = ${JSON.stringify(address)};\nexport const CONTRACT_ABI = ${JSON.stringify(artifact.abi, null, 2)};\nexport const NETWORK = {\n  chainId: 80002,\n  name: "Polygon Amoy Testnet",\n  rpcUrl: "https://rpc-amoy.polygon.technology/",\n  explorer: "https://amoy.polygonscan.com/",\n};\n`
    );

    console.log("📁 Saved to frontend/src/config/constants.js");
    console.log("🎉 Deployment successful!");
  } catch (error) {
    console.error("❌ Deployment failed:", error);
    process.exitCode = 1;
  }
}

main();
