import hre from "hardhat";
import fs from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const artifactPath = path.resolve(
  __dirname,
  "../artifacts/contracts/CertificateRegistry.sol/CertificateRegistry.json"
);
const constantsPath = path.resolve(
  __dirname,
  "../../frontend/src/config/constants.js"
);

async function main() {
  try {
    console.log("🚀 Deploying CertificateRegistry...");

    // Hardhat 3 — network connection
    const connection = await hre.network.getOrCreate();
    const { ethers } = connection;

    // Get signers — Hardhat 3 style
    const signers = await ethers.getSigners();
    const deployer = signers[0];

    if (!deployer) {
      throw new Error("No deployer signer found. Check your PRIVATE_KEY in .env");
    }

    const balance = await ethers.provider.getBalance(deployer.address);
    console.log(`📬 Deployer: ${deployer.address}`);
    console.log(`💰 Balance: ${ethers.formatEther(balance)} POL`);

    if (Number(ethers.formatEther(balance)) < 0.001) {
      throw new Error("Insufficient POL balance. Get test POL from faucet.");
    }

    // Deploy contract
    const Registry = await ethers.getContractFactory("CertificateRegistry");
    const registry = await Registry.deploy();
    await registry.waitForDeployment();

    const address = await registry.getAddress();
    const receipt = await registry.deploymentTransaction()?.wait();

    console.log(`✅ Contract deployed to: ${address}`);
    console.log(`📦 Block number: ${receipt?.blockNumber ?? "unknown"}`);

    // Read artifact and write constants.js
    const artifact = JSON.parse(await fs.readFile(artifactPath, "utf8"));
    await fs.mkdir(path.dirname(constantsPath), { recursive: true });

    const constantsContent = `// Auto-generated by deploy script
// Generated at: ${new Date().toISOString()}

export const CONTRACT_ADDRESS = ${JSON.stringify(address)};

export const CONTRACT_ABI = ${JSON.stringify(artifact.abi, null, 2)};

export const NETWORK = {
  chainId: "0x13882",
  chainName: "Polygon Amoy Testnet",
  rpcUrls: ["https://rpc-amoy.polygon.technology/"],
  nativeCurrency: { name: "POL", symbol: "POL", decimals: 18 },
  blockExplorerUrls: ["https://amoy.polygonscan.com/"]
};
`;

    await fs.writeFile(constantsPath, constantsContent);

    console.log("📁 Saved to frontend/src/config/constants.js");
    console.log("🎉 Deployment successful!");
    console.log("");
    console.log("📋 Contract Address:", address);
    console.log("🔗 View on Explorer: https://amoy.polygonscan.com/address/" + address);
  } catch (error) {
    console.error("❌ Deployment failed:", error);
    process.exitCode = 1;
  }
}

main();