import hre from "hardhat";
import fs from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const artifactsDir = path.resolve(__dirname, "../artifacts/contracts");
const constantsPath = path.resolve(
  __dirname,
  "../../frontend/src/config/constants.js"
);

async function deployContract(ethers, name) {
  console.log(`\n🚀 Deploying ${name}...`);
  const Factory = await ethers.getContractFactory(name);
  const contract = await Factory.deploy();
  await contract.waitForDeployment();

  const address = await contract.getAddress();
  const receipt = await contract.deploymentTransaction()?.wait();

  console.log(`✅ ${name} deployed to: ${address}`);
  console.log(`📦 Block: ${receipt?.blockNumber ?? "unknown"}`);

  return { name, address };
}

async function loadABI(contractName, folderName) {
  const artifactPath = path.resolve(
    artifactsDir,
    folderName,
    `${contractName}.json`
  );
  const artifact = JSON.parse(await fs.readFile(artifactPath, "utf8"));
  return artifact.abi;
}

async function main() {
  try {
    console.log("🚀 Deploying Satya-Chain Multi-Sector Contracts...");

    const { ethers } = await hre.network.getOrCreate();
    const signers = await ethers.getSigners();
    const deployer = signers[0];

    if (!deployer) {
      throw new Error("No deployer signer found. Check your PRIVATE_KEY in .env");
    }

    const balance = await ethers.provider.getBalance(deployer.address);
    console.log(`📬 Deployer: ${deployer.address}`);
    console.log(`💰 Balance: ${ethers.formatEther(balance)} POL`);

    if (Number(ethers.formatEther(balance)) < 0.001) {
      throw new Error("Insufficient POL balance. Get test POL from faucet.");
    }

    // ============================================
    // Deploy all 4 contracts
    // ============================================
    const results = [];

    results.push(await deployContract(ethers, "CertificateRegistry"));
    results.push(await deployContract(ethers, "GovernmentRegistry"));
    results.push(await deployContract(ethers, "HealthcareRegistry"));
    results.push(await deployContract(ethers, "LandRegistry"));

    // ============================================
    // Load ABIs
    // ============================================
    const abiEducation = await loadABI("CertificateRegistry", "CertificateRegistry.sol");
    const abiGovernment = await loadABI("GovernmentRegistry", "GovernmentRegistry.sol");
    const abiHealthcare = await loadABI("HealthcareRegistry", "HealthcareRegistry.sol");
    const abiLand = await loadABI("LandRegistry", "LandRegistry.sol");

    // ============================================
    // Write constants.js
    // ============================================
    const addresses = {
      education: results[0].address,
      government: results[1].address,
      healthcare: results[2].address,
      land: results[3].address
    };

    const constantsContent = `// Auto-generated by deploy script
// Generated at: ${new Date().toISOString()}
// Network: Hardhat Local (localhost)

// ============================================
// CONTRACT ADDRESSES (Multi-Sector)
// ============================================
export const CONTRACT_ADDRESSES = {
  education: ${JSON.stringify(addresses.education)},
  government: ${JSON.stringify(addresses.government)},
  healthcare: ${JSON.stringify(addresses.healthcare)},
  land: ${JSON.stringify(addresses.land)}
};

// Backwards compatibility
export const CONTRACT_ADDRESS = CONTRACT_ADDRESSES.education;

// ============================================
// CONTRACT ABIs
// ============================================
export const CONTRACT_ABIS = {
  education: ${JSON.stringify(abiEducation, null, 2)},
  government: ${JSON.stringify(abiGovernment, null, 2)},
  healthcare: ${JSON.stringify(abiHealthcare, null, 2)},
  land: ${JSON.stringify(abiLand, null, 2)}
};

// Backwards compatibility
export const CONTRACT_ABI = CONTRACT_ABIS.education;

// ============================================
// NETWORK
// ============================================
export const NETWORK = {
  chainId: "0x7A69",
  chainName: "Hardhat Local",
  rpcUrls: ["http://127.0.0.1:8545"],
  nativeCurrency: { name: "ETH", symbol: "ETH", decimals: 18 },
  blockExplorerUrls: []
};
`;

    await fs.mkdir(path.dirname(constantsPath), { recursive: true });
    await fs.writeFile(constantsPath, constantsContent);

    console.log("\n📁 Saved to frontend/src/config/constants.js");
    console.log("🎉 All 4 contracts deployed successfully!");
    console.log("\n📋 Contract Addresses:");
    console.log("   Education:  ", addresses.education);
    console.log("   Government: ", addresses.government);
    console.log("   Healthcare: ", addresses.healthcare);
    console.log("   Land:       ", addresses.land);
  } catch (error) {
    console.error("❌ Deployment failed:", error);
    process.exitCode = 1;
  }
}

main();